rust: remove call to `bindings::errname` when building `testlib`
This allows us to use, for example, `Result::unwrap` from example code
and still be able to compile, link, and run the example.

Without this change, an attempt to use `unwrap` in an example results in
the following error when making `rusttest`:

```
rust/kernel/error.rs:360: undefined reference to `errname'

= help: some `extern` functions couldn't be found; some native libraries
may need to be installed or have their path specified
```

Signed-off-by: Wedson Almeida Filho <wedsonaf@google.com>