rust: module: improve parsing and errors
  - Simplified code.

  - Repeated keys are not allowed anymore, e.g.

        module! {
            type: RustMinimal,
            type: RustMinimal,
        ...

  - Better error messages:

        error: proc macro panicked
          --> ../samples/rust/rust_minimal.rs:10:1
           |
        10 | / module! {
        11 | |     type: RustMinimal,
        12 | |     name: b"rust_minimal",
        13 | |     description: b"Rust minimal sample",
        14 | |     author: b"Rust for Linux Contributors",
        15 | |     license: b"GPL v2",
        16 | | }
           | |_^
           |
           = help: message: Keys are not ordered as expected. Order them like: ["type", "name", "author", "description", "license"]

        error: proc macro panicked
          --> ../samples/rust/rust_minimal.rs:10:1
           |
        10 | / module! {
        11 | |     typo: RustMinimal,
        12 | |     name: b"rust_minimal",
        13 | |     author: b"Rust for Linux Contributors",
        14 | |     description: b"Rust minimal sample",
        15 | |     license: b"GPL v2",
        16 | | }
           | |_^
           |
           = help: message: Unknown key "typo". Valid keys are: ["type", "name", "author", "description", "license", "alias", "alias_rtnl_link", "params"].

        error: proc macro panicked
          --> ../samples/rust/rust_minimal.rs:10:1
           |
        10 | / module! {
        11 | |     type: RustMinimal,
        12 | |     name: b"rust_minimal",
        13 | |     author: b"Rust for Linux Contributors",
        14 | |     description: b"Rust minimal sample",
        15 | | }
           | |_^
           |
           = help: message: Missing required key "license".

        error: proc macro panicked
          --> ../samples/rust/rust_minimal.rs:10:1
           |
        10 | / module! {
        11 | |     type: RustMinimal,
        12 | |     name: b"rust_minimal",
        13 | |     license: b"GPL v2",
        14 | |     license: b"GPL v2",
        15 | | }
           | |_^
           |
           = help: message: Duplicated key "license". Keys can only be specified once.

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>