rust: bindgen: ignore RISC-V extensions for GCC builds
Clang does not recognize some of the new `-march` arguments
GCC accepts, and which the kernel uses since commit 6df2a016c0c8
("riscv: fix build with binutils 2.38"), thus `bindgen` fails
with a message like:

    error: invalid arch name 'rv64imac_zicsr_zifencei_zihintpause',
    unsupported standard user-level extension 'zicsr', err: true

The temporary solution is to ignore it -- yet another hack on top
of the existing ones for GCC builds.

This is needed to update the CI to the new Ubuntu 22.04 base images
which come with a newer GCC.

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>